#ifndef NETWORK_STORAGE_H
#define NETWORK_STORAGE_H

#include <stdint.h>

#define NETWORK_STORAGE_CONTACT_SIZE 5
#define NETWORK_STORAGE_TOTAL_BYTES CONFIG_DSA_NETWORK_STORAGE_TOTAL_BYTES
#define NETWORK_STORAGE_SECTOR_BYTES 4096
#define NETWORK_STORAGE_NVS_RESERVED_BYTES 64
#define NETWORK_STORAGE_RESERVED_SECTORS 2
#define NETWORK_STORAGE_BLOCK_BYTES \
	(NETWORK_STORAGE_SECTOR_BYTES - NETWORK_STORAGE_NVS_RESERVED_BYTES)
#define NETWORK_STORAGE_BLOCK_OVERHEAD 12
#define NETWORK_STORAGE_BLOCK_DATA_LEN \
	(((NETWORK_STORAGE_BLOCK_BYTES - NETWORK_STORAGE_BLOCK_OVERHEAD) / \
	  NETWORK_STORAGE_CONTACT_SIZE) * NETWORK_STORAGE_CONTACT_SIZE)
#define NETWORK_STORAGE_BLOCK_CONTACTS \
	(NETWORK_STORAGE_BLOCK_DATA_LEN / NETWORK_STORAGE_CONTACT_SIZE)
#define NETWORK_STORAGE_BLOCK_COUNT \
	((NETWORK_STORAGE_TOTAL_BYTES / NETWORK_STORAGE_SECTOR_BYTES) - \
	 NETWORK_STORAGE_RESERVED_SECTORS)

int network_storage_init(void);
int network_storage_append_block(const uint8_t *data, uint16_t len);
int network_storage_peek(uint8_t *buffer, uint16_t buffer_len,
			 uint16_t *bytes_written);
int network_storage_drop(uint16_t bytes_to_drop);
int network_storage_get_contact_count(uint32_t *count);
int network_storage_sync(void);

#endif /* NETWORK_STORAGE_H */
