# DSA project-specific build configuration.

CONFIG_DSA_DEV_SYNTHETIC_CONTACTS=y

CONFIG_DSA_LED_BLINK_ON_MS=30
CONFIG_DSA_SELF_REPORT_LED_ON_MS=2000

CONFIG_DSA_NETWORK_CONTACT_RING_COUNT=24000
CONFIG_DSA_NETWORK_STATUS_UPDATE_DELAY_MS=300
CONFIG_DSA_NETWORK_RAM_FLUSH_THRESHOLD=23000
CONFIG_DSA_NETWORK_STORAGE_TOTAL_BYTES=0xc5000

CONFIG_DSA_NUS_IDLE_TIMEOUT_MS=20000

CONFIG_DSA_SELF_REPORT_LONG_PRESS_MS=3000
CONFIG_DSA_SELF_REPORT_RING_COUNT=100
CONFIG_DSA_SELF_REPORT_FLUSH_THRESHOLD=75
CONFIG_DSA_SELF_REPORT_FLUSH_BATCH=64
CONFIG_DSA_SELF_REPORT_FLUSH_RETRY_MS=5000
