# Defaults for parameters that can be changed at runtime and persisted.

CONFIG_DSA_DEFAULT_LED_ACTIVE=y

CONFIG_DSA_NETWORK_DEFAULT_RSSI_THRESHOLD=80
CONFIG_DSA_NETWORK_DEFAULT_TRACKING_ACTIVE=y

CONFIG_DSA_ADV_INTERVAL_MIN_MS=90
CONFIG_DSA_ADV_INTERVAL_MAX_MS=120
CONFIG_DSA_SCAN_WINDOW_MS=120
CONFIG_DSA_SCAN_INTERVAL_MS=10000
CONFIG_DSA_LOW_ACTIVITY_ADV_INTERVAL_MIN_MS=10000
CONFIG_DSA_LOW_ACTIVITY_ADV_INTERVAL_MAX_MS=10100
CONFIG_DSA_LOW_ACTIVITY_SCAN_WINDOW_MS=100
CONFIG_DSA_LOW_ACTIVITY_SCAN_INTERVAL_MS=10000
CONFIG_DSA_RADIO_DEFAULT_HIGH_ACTIVITY=y
